# Generated by Django 4.2.5 on 2023-10-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available", models.BooleanField(db_index=True, default=True)),
                (
                    "quantity",
                    models.IntegerField(
                        default=1, help_text="Enter the quantity of this service"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(choices=[("web", "Web Service")], max_length=20),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True, default="1 Month", max_length=50, null=True
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "available"], name="Product_ser_name_1bbf9a_idx"
                    )
                ],
            },
        ),
    ]
