# Generated by Django 4.2.5 on 2023-11-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available", models.BooleanField(db_index=True, default=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("premium", "Premium"), ("pro", "Pro")], max_length=20
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "available"], name="Product_ser_name_1bbf9a_idx"
                    )
                ],
            },
        ),
    ]
