# Generated by Django 4.2.5 on 2023-10-27 12:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceproduct",
            name="quantity",
        ),
    ]
