# Generated by Django 4.2.5 on 2023-10-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Product", "0002_remove_serviceproduct_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceproduct",
            name="description",
        ),
        migrations.AddField(
            model_name="serviceproduct",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="serviceproduct",
            name="category",
            field=models.CharField(
                choices=[("premium", "Premium"), ("pro", "Pro")], max_length=20
            ),
        ),
    ]
