# Generated by Django 4.2.5 on 2023-10-29 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Product", "0003_remove_serviceproduct_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serviceproduct",
            name="duration",
        ),
    ]
