# Generated by Django 4.2.5 on 2023-10-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserHub", "0004_searchservicecount_updated_at_usersearch_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersearch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
