# Generated by Django 4.2.5 on 2023-10-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserHub", "0005_usersearch_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="searchservicecount",
            options={"ordering": ("-updated_at",)},
        ),
        migrations.AlterModelOptions(
            name="usersearch",
            options={"ordering": ("-updated_at",)},
        ),
        migrations.AddField(
            model_name="searchservicecount",
            name="status",
            field=models.CharField(
                choices=[("basic", "Basic"), ("premium", "Premium"), ("pro", "Pro")],
                default="basic",
                max_length=100,
            ),
        ),
    ]
